# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: /:title

# Setup
title: SPF
description: "Sprites: a Practical Foundation<br><small>(AKA how to not get burned by sprites 🔥)</small>"
info: A small collection of example scripts showcasing different ways to
  use the Playdate''s sprite system.

url: https://gammagames.github.io/spf/
baseurl: /spf

author:
  name: 'Gamma'
  url: https://github.com/gammagames

# Custom vars
version: 1.0.0

github:
  repo: https://github.com/GammaGames/spf
